### ISSUE TITLE
metadataproviders is not set

### ISSUE THREAD

**Issue by brucellino** [osct/shibboleth-idp-v3#1]
in `configure.yml`, there is a task : 

``` yml
- name: Retrieve certificate for metadata providers
  get_url:
    url: "{{ item.certificate.url }}"
    dest: "{{ idp_home }}/metadata/{{ item.name }}.pem"
    mode: 0600
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
  when: item.certificate is defined and  item.certificate.url is defined
  notify: "{{ 'Restart tomcat'  if ansible_virtualization_type != 'docker' else 'Restart tomcat in docker' }}"
  with_items:
    - "{{ metadataproviders }}"
```

which seems to imply a list of metadata providers. When the playbook is run, however, this variable is undefined : 

```
 __________________________________________________________
< TASK [shibboleth-idp-v3 : Add metadata providers by url] >
 ----------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [idp.sagrid.ac.za]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'metadataproviders' is undefined"}
```

I don't see anywhere where this variable is set or registered - does it need to be passed on the command line ?
